apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: auth-service
  namespace: foo
spec:
  hosts:
  - auth-service
  ports:
  - number: 5000
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: {AUTH-SERVICE-HOST}
  location: MESH_EXTERNAL