apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: authz-filter
  namespace: foo
spec:
  deployment:
    istio:
      kind: Deployment
  filter:
    config: authn-service
    image: webassemblyhub.io/jianshao/authz-filter:{FILTER_VERSION}