apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: auth-filter
  namespace: foo
spec:
  deployment:
    istio:
      kind: Deployment
  filter:
    config: auth-service
    image: webassemblyhub.io/jianshao/auth-filter:{FILTER_VERSION}
